//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyLoadingvsEagerLoading
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int UrunID { get; set; }
        public string UrunIsmi { get; set; }
        public string Ram { get; set; }
        public string HardDisk { get; set; }
        public string Yazar { get; set; }
        public string Kumas { get; set; }
        public string Renk { get; set; }
    }
}
